### ISSUE TITLE
Getting Error while Creating a build 

### ISSUE THREAD

**Issue by navaganeshr** [matsp/docker-flutter#12]
### Command i used: 
`docker run --rm -e UID=$(id -u) -e GID=$(id -g) --net=host --workdir /project -v "$PWD":/project matspfeiffer/flutter build appbundle `

### Error: 

ERR : Git error. Command: `git clone --mirror https://github.com/Cretezy/flutter_cached_network_image.git /home/developer/flutter/.pub-cache/git/cache/flutter_cached_network_image-7f036d743d57f9efd52207eb3becce37cff9ace7`

    | stdout: 

    | stderr: Cloning into bare repository '/home/developer/flutter/.pub-cache/git/cache/flutter_cached_network_image-7f036d743d57f9efd52207eb3becce37cff9ace7'...

    | fatal: could not read Username for 'https://github.com': No such device or address

    | exit code: 128

**Comment by matsp** [comment]
Looks like the error is coming from one of your packages while fetching something from github.
