### ISSUE TITLE
running on iOS?

### ISSUE THREAD

**Issue by sultanmyrza** [matsp/docker-flutter#20]
I'm using mac and develop my flutter app and test in iOS simulator and iOS device(via cable) 

Is it possible to use docker-flutter on mac to build, run on iOS simulator or iOS device (via cable or wireless)?

```
[✓] Flutter (Channel stable, 2.0.6, on Mac OS X 10.15.7 19H2 darwin-x64, locale
    en)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.1)
[✓] VS Code (version 1.57.0)
[✓] Connected device (2 available)
    ! Error: sultanmyrza’s iPhone is not connected. Xcode will continue when
      sultanmyrza’s iPhone is connected. (code -13)
```

**Comment by matsp** [comment]
Hi! 

> With this docker image you don't need to install the Flutter and Android SDK on your developer machine.

What you want to archive is actually not possible with this image. I'am not sure how the build pipeline is looking for macOS but I guess your Xcode need direct access to build and deploy the app to the simulator or device.

In other words: If you want to develop iOS apps on macOS then you don't need this image. If you want to develop android apps on macOS you can use this image to avoid the SDK installation or make the development process easier in your team with fixed setups.
