### ISSUE TITLE
Connecting to device on windows [help wanted]

### ISSUE THREAD

**Issue by nandordudas** [matsp/docker-flutter#24]
Hello,

I'm using the `.devcontainer` alternative on windows, but I can't connect to device wirelessly.

I have tried commands below - these doesn't work me.

```bash
ip=...
port=...
adb kill-server
# ...application running on port 5037
adb tcpip 5555
# error: no devices/emulators found
adb connect "${ip}"
# failed to connect to '$ip:$port': Connection refused
adb devices
# No devices detected.
#
# Wireless debugging on android 11
adb pair "${ip}:${port}"
# Successfully paired
adb devices
# No devices detected.
```

Have you any idea for me? Thank you in advance!

> If development softwares installed on system (platform tools, etc.), I can connect

**Comment by nandordudas** [comment]
Solved.
But don't know, how to reproduce the problem - yet.

**Comment by matsp** [comment]
Maybe some confusion around the port mappings ;)

**Comment by nandordudas** [comment]
I dont know.
I tryed with fresh installed os with multiple times, multiple accounts.
Last time I installed scoop and install flutter with it, try to connect to phone wirelessly and after few seconds phone name appears inside devcontainer.

Weird thing is pair was successful but cannot connect wirelessly.

Thanks for your help, have a nice day ;)
