### ISSUE TITLE
Omit update check by default

### ISSUE THREAD

**Issue by x29a** [matsp/docker-flutter#9]
Hey,

what is your opinion on omitting the flutter update check on startup?

Id argue that since the container is disposed after each call, manual upgrading doesnt make any sense and the update check takes quite a while on each run.

This would also contribute towards #5 for faster container startup times.

The appropriate flag is `--no-version-check` (see [here](https://github.com/flutter/flutter/issues/59533#issuecomment-648432478)).

After all, the `flutter upgrade` call works nevertheless if people need it (e.g. for persistent containers).

**Comment by matsp** [comment]
Sounds like a good idea ☺️

**Comment by x29a** [comment]
Ill send in the PR soon then, thanks for your feedback!
